PROCESS_TERMINATE                  =0x0001  
PROCESS_CREATE_THREAD              =0x0002  
PROCESS_SET_SESSIONID              =0x0004  
PROCESS_VM_OPERATION               =0x0008  
PROCESS_VM_READ                    =0x0010  
PROCESS_VM_WRITE                   =0x0020  
PROCESS_DUP_HANDLE                 =0x0040  
PROCESS_CREATE_PROCESS             =0x0080  
PROCESS_SET_QUOTA                  =0x0100  
PROCESS_SET_INFORMATION            =0x0200  
PROCESS_QUERY_INFORMATION          =0x0400  
PROCESS_SUSPEND_RESUME             =0x0800  
PROCESS_QUERY_LIMITED_INFORMATION  =0x1000  
PROCESS_SET_LIMITED_INFORMATION    =0x2000 

DEFAULT_ACCESS_P = \
    PROCESS_QUERY_INFORMATION | \
    PROCESS_VM_READ | \
    PROCESS_VM_WRITE | \
    PROCESS_VM_OPERATION | \
    PROCESS_CREATE_THREAD | \
    PROCESS_SET_QUOTA | \
    PROCESS_TERMINATE | \
    PROCESS_SUSPEND_RESUME | \
    PROCESS_DUP_HANDLE

eModType_mt_mod32 = 0  
eModType_mt_mod64 = 1  
eModType_mt_default = 2 
eModType_mt_unknown = 3

eModSeachType_LdrList = 0
eModSeachType_Sections = 1
eModSeachType_PEHeaders = 2
